"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from datetime import timedelta   # ⭐ ADD THIS
import mimetypes
import os
from dotenv import load_dotenv
import dj_database_url
mimetypes.add_type("text/css", ".css", True)

load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-secret-key-change-this-in-production') 
DEBUG = True
ALLOWED_HOSTS = ['*']


# ---------------------------------------------------------------
# ⭐ ADD THE REQUIRED APPS HERE
# ---------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ⭐ ADD THESE 3 LINES
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'storages',     # ⭐ ADD THIS
    'api',          # <-- your API app
    'homepage',     # <-- your homepage/public page app
]

# ---------------------------------------------------------------
# MIDDLEWARE (leave as default)
# ---------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'core.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # you can add template dirs later
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ---------------------------------------------------------------
# DATABASE (leave as default)
# ---------------------------------------------------------------


DATABASES = {
    'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
}


# ---------------------------------------------------------------
# PASSWORD VALIDATION (leave as default)
# ---------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------
# INTERNATIONALIZATION (default)
# ---------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'frontend' ]
STATIC_ROOT = BASE_DIR / 'static'

# Media Files (Uploads)
MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'  <-- Commented out for S3

# Supabase Storage (S3 Compatible)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'media'
AWS_S3_ENDPOINT_URL = 'https://tyeszjpfmtmftibxibwj.supabase.co/storage/v1/s3'
AWS_S3_REGION_NAME = 'ap-southeast-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_CUSTOM_DOMAIN = 'tyeszjpfmtmftibxibwj.supabase.co/storage/v1/object/public/media'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        # "OPTIONS": {
        #     "access_key": SUPABASE_ACCESS_KEY_ID,
        #     "secret_key": SUPABASE_SECRET_ACCESS_KEY,
        #     "bucket_name": SUPABASE_STORAGE_BUCKET_NAME,
        #     "endpoint_url": SUPABASE_S3_ENDPOINT_URL,
        #     "region_name": SUPABASE_S3_REGION_NAME,
        #     "file_overwrite": SUPABASE_S3_FILE_OVERWRITE,
        #     "default_acl": SUPABASE_DEFAULT_ACL,
        #     "querystring_auth": SUPABASE_QUERYSTRING_AUTH,
        #     "addressing_style": SUPABASE_S3_ADDRESSING_STYLE,
        #     "custom_domain": SUPABASE_S3_CUSTOM_DOMAIN,
        # },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ---------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# ---------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------
# ⭐ ADD DJANGO REST FRAMEWORK CONFIG HERE
# ---------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


# ---------------------------------------------------------------
# ⭐ ADD SIMPLE JWT CONFIG HERE
# ---------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}



