# Generated by Django 5.2.8 on 2025-12-09 11:33

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_profile_github_profile_gmail_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, validators=[homepage.models.Profile.validate_github]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, validators=[homepage.models.Profile.validate_instagram]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, validators=[homepage.models.Profile.validate_linkedin]),
        ),
    ]
