# Generated by Django 6.0 on 2025-12-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='homepage.photocomment'),
        ),
    ]
